# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160422092405 on 2016-04-22 09:31
from __future__ import unicode_literals

from django.db import migrations
import inventorum.ebay.lib.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20160315_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='original_ebay_data',
            field=inventorum.ebay.lib.db.fields.JSONField(null=True, verbose_name='Original ebay data'),
        ),
    ]
