# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160422092405 on 2016-04-22 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20160315_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayaccountmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ebayaccountmodel',
            name='payment_method_paypal_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
