# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160422092405 on 2016-04-22 09:31
from __future__ import unicode_literals

from django.db import migrations
import inventorum.ebay.lib.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_dirtynessregistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayapiattemptrequest',
            name='headers',
            field=inventorum.ebay.lib.db.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='ebayapiattemptresponse',
            name='headers',
            field=inventorum.ebay.lib.db.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='ebayitemmodel',
            name='publishing_status_details',
            field=inventorum.ebay.lib.db.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ebayitemupdatemodel',
            name='status_details',
            field=inventorum.ebay.lib.db.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ebayitemvariationupdatemodel',
            name='status_details',
            field=inventorum.ebay.lib.db.fields.JSONField(blank=True, null=True),
        ),
    ]
